# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainDialog(object):
    def setupUi(self, MainDialog):
        MainDialog.setObjectName("MainDialog")
        MainDialog.resize(760, 656)
        self.lblLiveView = QtWidgets.QLabel(MainDialog)
        self.lblLiveView.setGeometry(QtCore.QRect(10, 10, 741, 480))
        self.lblLiveView.setObjectName("lblLiveView")
        self.btnRegister = QtWidgets.QPushButton(MainDialog)
        self.btnRegister.setGeometry(QtCore.QRect(20, 530, 171, 28))
        self.btnRegister.setObjectName("btnRegister")
        self.btnReTrain = QtWidgets.QPushButton(MainDialog)
        self.btnReTrain.setGeometry(QtCore.QRect(350, 530, 171, 28))
        self.btnReTrain.setObjectName("btnReTrain")
        self.txtRegisterName = QtWidgets.QLineEdit(MainDialog)
        self.txtRegisterName.setGeometry(QtCore.QRect(70, 590, 211, 22))
        self.txtRegisterName.setObjectName("txtRegisterName")
        self.lblRegisterName = QtWidgets.QLabel(MainDialog)
        self.lblRegisterName.setGeometry(QtCore.QRect(20, 590, 51, 21))
        self.lblRegisterName.setObjectName("lblRegisterName")
        self.lblRegisterCode = QtWidgets.QLabel(MainDialog)
        self.lblRegisterCode.setGeometry(QtCore.QRect(20, 620, 51, 21))
        self.lblRegisterCode.setObjectName("lblRegisterCode")
        self.txtRegisterCode = QtWidgets.QLineEdit(MainDialog)
        self.txtRegisterCode.setGeometry(QtCore.QRect(70, 620, 211, 22))
        self.txtRegisterCode.setObjectName("txtRegisterCode")
        self.btnExit = QtWidgets.QPushButton(MainDialog)
        self.btnExit.setGeometry(QtCore.QRect(580, 620, 171, 28))
        self.btnExit.setObjectName("btnExit")
        self.btnRun = QtWidgets.QPushButton(MainDialog)
        self.btnRun.setGeometry(QtCore.QRect(580, 530, 171, 28))
        self.btnRun.setObjectName("btnRun")
        self.btnRegenerateFeatures = QtWidgets.QPushButton(MainDialog)
        self.btnRegenerateFeatures.setGeometry(QtCore.QRect(200, 530, 141, 28))
        self.btnRegenerateFeatures.setObjectName("btnRegenerateFeatures")

        self.retranslateUi(MainDialog)
        QtCore.QMetaObject.connectSlotsByName(MainDialog)

    def retranslateUi(self, MainDialog):
        _translate = QtCore.QCoreApplication.translate
        MainDialog.setWindowTitle(_translate("MainDialog", "Dialog"))
        self.lblLiveView.setText(_translate("MainDialog", "TextLabel"))
        self.btnRegister.setText(_translate("MainDialog", "Start Register"))
        self.btnReTrain.setText(_translate("MainDialog", "Train"))
        self.lblRegisterName.setText(_translate("MainDialog", "Name:"))
        self.lblRegisterCode.setText(_translate("MainDialog", "Code:"))
        self.btnExit.setText(_translate("MainDialog", "Exit"))
        self.btnRun.setText(_translate("MainDialog", "Run"))
        self.btnRegenerateFeatures.setText(_translate("MainDialog", "Generate Feature Vector"))
